### ISSUE TITLE
Create POCO classes from database

### ISSUE THREAD

**Issue by TheJuki** [IS-Chili/chili#3]
If using SQL Server, this should be straight-forward using database-first:
https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db

If using MySQL, refer to these:
https://www.nuget.org/packages/MySql.Data.EntityFrameworkCore
https://dev.mysql.com/doc/connector-net/en/connector-net-entityframework-core.html

**Comment by RussCantrell** [comment]
I'm not familiar with POCO, but do have a full version of SQL Server installed if that is helpful. (I believe most are using MySQL?)

**Comment by TheJuki** [comment]
This is actually already done for MySQL. See here: https://github.com/IS-Chili/chili/tree/master/Usa.chili.Domain

We may want to remove the classes that won't be used in the new code such as the 202 classes.

So, this can be closed.

Also, go here to accept your invitation at the top: https://github.com/IS-Chili

**Comment by RussCantrell** [comment]
Invitation accepted. Thanks.
